trigger:
- master

resources:
  repositories:
    - repository: flatris
      type: github
      name: nigelhenn/flatris
      ref: refs/heads/master
      endpoint: GitHub-flatris  # Replace with your actual service connection name

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install eslint-plugin-import@latest --save-dev
    npm install --legacy-peer-deps
    npm install env-cmd --save-dev

    if [ -f .env ]; then
      echo ".env file found, using env-cmd"
      npx env-cmd next build web
    else
      echo "No .env file found, running build without env-cmd"
      npm run build
    fi
  displayName: 'Install dependencies and build project'
