trigger:
- master

resources:
  repositories:
    - repository: flatris
      type: github
      name: nigelhenn/flatris
      ref: refs/heads/master
      endpoint: Github-Flatris  # Replace with your actual service connection name
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    # Upgrade eslint-plugin-import to fix peer conflict
    npm install eslint-plugin-import@latest --save-dev

    # Install all dependencies safely
    npm install --legacy-peer-deps

    # Install env-cmd locally
    npm install env-cmd --save-dev

    # Check for .env file before using env-cmd
    if [ -f .env ]; then
      echo ".env file found, using env-cmd"
      npx env-cmd next build web
    else
      echo "No .env file found, running build without env-cmd"
      npm run build
    fi
  displayName: 'Install dependencies and build project'
