trigger:
- master

resources:
  repositories:
    - repository: flatris
      type: github
      name: nigelhenn/flatris
      ref: refs/heads/main
      endpoint: GitHubConnection  # Replace with your actual service connection name

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm install env-cmd --save-dev
    npm run build
  displayName: 'Install dependencies and build project'

